import { SingleAlertConfig } from '../types';

export function createDefaultSingleAlert(type: 'follow' | 'sub' | 'gift' | 'raid' | 'tip' | 'cheer'): SingleAlertConfig {
  switch (type) {
    case 'follow':
      return {
        enabled: true,
        messageTemplate: '{user} ¡Ahora te sigue!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3',
        soundVolume: 0.8,
        duration: 6,
        animation: 'bounce',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#53FC18',
        glowColor: '#53FC18',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
    case 'sub':
      return {
        enabled: true,
        messageTemplate: '{user} ¡Se ha suscrito al canal!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/26AHONQ79FdWZhAI0/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/2019/2019-preview.mp3',
        soundVolume: 0.85,
        duration: 7,
        animation: 'zoom',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#9146FF',
        glowColor: '#9146FF',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
    case 'gift':
      return {
        enabled: true,
        messageTemplate: '{user} regaló {amount} suscripciones!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/2018/2018-preview.mp3',
        soundVolume: 0.9,
        duration: 7,
        animation: 'slide',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#EC4899',
        glowColor: '#EC4899',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
    case 'raid':
      return {
        enabled: true,
        messageTemplate: '{user} llegó con una raid de {amount} personas!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/1435/1435-preview.mp3',
        soundVolume: 0.9,
        duration: 8,
        animation: 'flip',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#F59E0B',
        glowColor: '#F59E0B',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
    case 'tip':
      return {
        enabled: true,
        messageTemplate: '{user} envió una donación de ${amount}!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/67ThDxtWS4Y92/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/2017/2017-preview.mp3',
        soundVolume: 0.9,
        duration: 7,
        animation: 'pulse',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#10B981',
        glowColor: '#10B981',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
    case 'cheer':
      return {
        enabled: true,
        messageTemplate: '{user} envió {amount} bits!',
        mediaType: 'gif',
        mediaUrl: 'https://media.giphy.com/media/l41lT4n6ylgW2hh04/giphy.gif',
        soundUrl: 'https://assets.mixkit.co/active_storage/sfx/2020/2020-preview.mp3',
        soundVolume: 0.85,
        duration: 6,
        animation: 'bounce',
        layout: 'top-bottom',
        cardStyle: 'transparent',
        showBorder: false,
        showGlow: false,
        showBadge: false,
        showConfetti: true,
        textColor: '#ffffff',
        titleColor: '#06B6D4',
        glowColor: '#06B6D4',
        fontSize: 26,
        mediaSize: 180,
        ttsEnabled: false,
        ttsVoice: 'es-ES',
        ttsVolume: 0.8,
      };
  }
}
